export const currencies = [
    { code: 'AFN', name: 'Afghanistan Afghani', flag: '🇦🇫' },
    { code: 'ALL', name: 'Albanian Lek', flag: '🇦🇱' },
    { code: 'DZD', name: 'Algerian Dinar', flag: '🇩🇿' },
    { code: 'AOA', name: 'Angolan Kwanza', flag: '🇦🇴' },
    { code: 'ARS', name: 'Argentine Peso', flag: '🇦🇷' },
    { code: 'AUD', name: 'Australian Dollar', flag: '🇦🇺' },
    { code: 'AZN', name: 'Azerbaijan Manat', flag: '🇦🇿' },
    { code: 'BSD', name: 'Bahamian Dollar', flag: '🇧🇸' },
    { code: 'BBD', name: 'Barbadian Dollar', flag: '🇧🇧' },
    { code: 'BYN', name: 'Belarusian Ruble', flag: '🇧🇾' },
    { code: 'BZD', name: 'Belize Dollar', flag: '🇧🇿' },
    { code: 'BMD', name: 'Bermudian Dollar', flag: '🇧🇲' },
    { code: 'BOB', name: 'Boliviano', flag: '🇧🇴' },
    { code: 'BAM', name: 'Bosnia-Herzegovina Convertible Mark', flag: '🇧🇦' },
    { code: 'BWP', name: 'Botswana Pula', flag: '🇧🇼' },
    { code: 'BRL', name: 'Brazilian Real', flag: '🇧🇷' },
    { code: 'GBP', name: 'British Pound Sterling', flag: '🇬🇧' },
    { code: 'CAD', name: 'Canadian Dollar', flag: '🇨🇦' },
    { code: 'CLP', name: 'Chilean Peso', flag: '🇨🇱' },
    { code: 'CNY', name: "Chinese Yuan Renminbi", flag:' 🇨🇳'},
    { code:'COP',name:'Colombian Peso',flag:' 🇨︎'},
    // Add more currencies as needed
];
